<?php

/**
 * @file
 * Primary module hooks for weather module.
 */

/**
 * Implements hook_theme().
 */
function weather_theme() {
  return [
    'weather' => [
      'variables' => [
        'name' => NULL,
        'temperature' => NULL,
        'icon' => NULL,
      ],
    ],
  ];
}

/**
 * Example of adding variables with preprocess.
 */
function weather_preprocess_weather(&$variables) {

  $variable_name = 'example of preprocess';
  $variables['preprocess_example'] = $variable_name;

}
